package com.peplatform.portfolioservice.kafka.consumer;

import com.peplatform.portfolioservice.kafka.config.KafkaTopics;
import com.peplatform.portfolioservice.kafka.event.InvestmentCreatedEvent;
import com.peplatform.portfolioservice.kafka.model.KafkaMessageMetadata;
import com.peplatform.portfolioservice.kafka.service.KafkaFailureService;
import com.peplatform.portfolioservice.service.api.InvestmentAuditService;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import lombok.extern.slf4j.Slf4j;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.springframework.kafka.annotation.BackOff;
import org.springframework.kafka.annotation.DltHandler;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.annotation.RetryableTopic;
import org.springframework.kafka.retrytopic.DltStrategy;
import org.springframework.kafka.support.KafkaHeaders;
import org.springframework.messaging.handler.annotation.Header;
import org.springframework.stereotype.Component;

/**
 * An implementation of the InvestmentAuditConsumer class that handles events generated by InvestmentCreatedEvent.
 *
 * @author Randjith
 * @version 1.0.0
 * @email randjithkumar@no-reply.github.com
 * @date 2026-07-17
 * @since 0.0.1-SNAPSHOT
 */
@Slf4j
@Component
public class InvestmentAuditConsumer {

    /**
     * Investor audit service responsible for processing investment creation events.
     *
     * @see InvestmentAuditService
     */
    private final InvestmentAuditService investmentAuditService;

    private final KafkaFailureService kafkaFailureService;

    private final Counter consumed;

    private final Counter dlt;


    public InvestmentAuditConsumer(InvestmentAuditService investmentAuditService,
                                   KafkaFailureService kafkaFailureService,
                                   MeterRegistry meterRegistry) {
        this.investmentAuditService = investmentAuditService;
        this.kafkaFailureService = kafkaFailureService;
        this.consumed = Counter.builder("portfolio.kafka.consumer.processed")
                .description("Number of successfully processed Kafka events")
                .tag("topic", KafkaTopics.INVESTMENT_CREATED)
                .register(meterRegistry);

        this.dlt = Counter.builder("portfolio.kafka.consumer.dlt")
                .description("Number of Kafka events sent to DLT")
                .tag("topic", KafkaTopics.INVESTMENT_CREATED)
                .register(meterRegistry);
//        this.consumed = meterRegistry.counter("portfolio.kafka.consumer.processed", "topic", KafkaTopics.INVESTMENT_CREATED);
//        this.dlt = meterRegistry.counter("portfolio.kafka.consumer.dlt", "topic", KafkaTopics.INVESTMENT_CREATED);
    }

    /**
     * Consumes investment created events and processes them using the {@link InvestmentAuditService}.
     * The method handles potential exceptions by retrying with exponential backoff.
     *
     * @param event  The incoming investment created event
     * @param record The Kafka consumer record associated with the incoming event
     */
    @RetryableTopic(
            kafkaTemplate = "kafkaTemplate",
            attempts = "${spring.kafka.retry.attempts:4}",
            backOff = @BackOff(
                    delay = 3000,
                    multiplier = 2.0,
                    maxDelay = 10000
            ),
            retryTopicSuffix = "-retry",
            dltTopicSuffix = "-dlt",
            autoCreateTopics = "false",
            numPartitions = "${spring.kafka.partitions:3}",
            replicationFactor = "${spring.kafka.replication-factor:1}",
            dltStrategy = DltStrategy.FAIL_ON_ERROR
    )
    @KafkaListener(topics = KafkaTopics.INVESTMENT_CREATED,
            groupId = "${spring.kafka.consumer.group-id:portfolio-investment-audit-group}",
            concurrency = "${spring.kafka.consumer-concurrency:3}")
    public void consume(InvestmentCreatedEvent event, ConsumerRecord<String, InvestmentCreatedEvent> record) {
        KafkaMessageMetadata metaData = new KafkaMessageMetadata(record.topic(), record.partition(), record.offset());
        investmentAuditService.processInvestmentCreatedEvent(event, metaData);
        consumed.increment();
    }

    /**
     * Processes an investment creation event.
     *
     * <p>This method receives an investment created event, processes it according to the business rules,
     * and updates the necessary data. If an exception occurs during the processing, it is handled by propagating
     * the exception upstream.
     *
     * @param event The investment creation event
     */
    private void processAuditEvent(
            InvestmentCreatedEvent event
    ) {
        // This will later save to an audit table.
        // Throwing an exception here activates retry processing.

        if (event.investmentId() == null) {
            throw new IllegalArgumentException(
                    "Investment ID cannot be null"
            );
        }
    }

    /**
     * Consumes investment created events and processes them using the {@link InvestmentAuditService}.
     * The method handles potential exceptions by retrying with exponential backoff.
     *
     * @param event  The incoming investment created event
     * @param record The Kafka consumer record associated with the incoming event
     */
    @DltHandler
    public void processDltMessage(
            InvestmentCreatedEvent event,
            ConsumerRecord<String, InvestmentCreatedEvent> record,
            @Header(
                    name = KafkaHeaders.EXCEPTION_MESSAGE,
                    required = false
            ) String exceptionMessage
    ) {
        dlt.increment();

        String errorMessage =
                exceptionMessage == null || exceptionMessage.isBlank()
                        ? "Kafka retry attempts exhausted"
                        : exceptionMessage;

        kafkaFailureService.persist(
                event,
                record,
                new IllegalStateException(errorMessage)
        );

        log.error(
                "Kafka event moved to DLT: eventId={}, topic={}, partition={}, offset={}, error={}",
                event.eventId(),
                record.topic(),
                record.partition(),
                record.offset(),
                errorMessage
        );
    }
}