package com.peplatform.portfolioservice.kafka.event;

import com.peplatform.portfolioservice.common.enums.InvestmentStatus;

import java.time.Instant;
import java.util.UUID;

/**
 * A record class that represents an investment status change event, encapsulating the essential details needed for logging and tracing this event. This event is designed to provide a structured approach to managing such changes in the portfolio system.
 *
 * @author Randjith
 * @version 1.0.0
 * @since 0.0.1-SNAPSHOT
 */
public record InvestmentStatusChangedEvent(
        UUID eventId,
        String eventType,
        String eventVersion,
        String correlationId,
        Instant occurredAt,
        Long investmentId,
        Long investorId,
        Long fundId,
        InvestmentStatus previousStatus,
        InvestmentStatus newStatus,
        String changedBy
) implements PortfolioEvent {

    /**
     * Creates an {@link InvestmentStatusChangedEvent} with the specified parameters.
     *
     * @param correlationId  A unique identifier for the event, usually generated by a UUID.
     * @param investmentId   The ID of the investment affected.
     * @param investorId     The ID of the investor associated with the investment.
     * @param fundId         The ID of the fund associated with the investment.
     * @param previousStatus The previous status of the investment.
     * @param newStatus      The new status of the investment.
     * @param changedBy      The identity of the user who generated this event.
     * @return An {@link InvestmentStatusChangedEvent} instance representing the event.
     */
    public static InvestmentStatusChangedEvent create(
            String correlationId,
            Long investmentId,
            Long investorId,
            Long fundId,
            InvestmentStatus previousStatus,
            InvestmentStatus newStatus,
            String changedBy
    ) {
        return new InvestmentStatusChangedEvent(
                UUID.randomUUID(),
                "INVESTMENT_STATUS_CHANGED",
                "1.0",
                correlationId,
                Instant.now(),
                investmentId,
                investorId,
                fundId,
                previousStatus,
                newStatus,
                changedBy
        );
    }
}