CREATE TABLE application_users
(
    -- Primary Key using IDENTITY (matches GenerationType.IDENTITY)
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Core Columns with length constraints and null checks
    username           VARCHAR(100) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    role               VARCHAR(50)  NOT NULL,

    -- Boolean flags with default values matching @Builder.Default
    enabled            BOOLEAN      NOT NULL    DEFAULT TRUE,
    account_non_locked BOOLEAN      NOT NULL    DEFAULT TRUE,

    -- Standard BaseEntity columns (Adjust these to match your actual BaseEntity fields)
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(100),
    updated_by         VARCHAR(100),
    version            BIGINT       NOT NULL    DEFAULT 0,

    -- Constraints
    CONSTRAINT pk_application_users PRIMARY KEY (id),
    CONSTRAINT uk_application_users_username UNIQUE (username),
    CONSTRAINT uk_application_users_email UNIQUE (email)
);

CREATE TABLE investors
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_code    VARCHAR(50)    NOT NULL,
    full_name        VARCHAR(150)   NOT NULL,
    email            VARCHAR(255)   NOT NULL,
    country          VARCHAR(100)   NOT NULL,
    risk_profile     VARCHAR(50)    NOT NULL,
    committed_amount NUMERIC(18, 2) NOT NULL,

    created_at       TIMESTAMP      NOT NULL,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    version          BIGINT         NOT NULL DEFAULT 0,

    CONSTRAINT uk_investors_investor_code
        UNIQUE (investor_code),

    CONSTRAINT ck_investors_committed_amount
        CHECK (committed_amount > 0)
);

CREATE TABLE funds
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code      VARCHAR(50)    NOT NULL,
    fund_name      VARCHAR(200)   NOT NULL,
    asset_class    VARCHAR(50)    NOT NULL,
    currency       VARCHAR(3)     NOT NULL,
    nav            NUMERIC(18, 4) NOT NULL,
    inception_date DATE           NOT NULL,
    status         VARCHAR(30)    NOT NULL,

    created_at     TIMESTAMP      NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT         NOT NULL DEFAULT 0,

    CONSTRAINT uk_funds_fund_code
        UNIQUE (fund_code),

    CONSTRAINT ck_funds_nav
        CHECK (nav > 0),

    CONSTRAINT ck_funds_currency
        CHECK (char_length(currency) = 3),

    CONSTRAINT ck_funds_status
        CHECK (status IN ('ACTIVE', 'CLOSED', 'SUSPENDED')),

    CONSTRAINT ck_funds_asset_class
        CHECK (
            asset_class IN (
                            'PRIVATE_EQUITY',
                            'REAL_ESTATE',
                            'INFRASTRUCTURE',
                            'PRIVATE_DEBT',
                            'HEDGE_FUND'
                )
            )
);

CREATE TABLE investments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investor_id     BIGINT         NOT NULL,
    fund_id         BIGINT         NOT NULL,

    amount          NUMERIC(18, 2) NOT NULL,
    nav             NUMERIC(18, 4) NOT NULL,
    units           NUMERIC(18, 4) NOT NULL,
    status          VARCHAR(30)    NOT NULL,
    investment_date TIMESTAMP      NOT NULL,

    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    version         BIGINT         NOT NULL DEFAULT 0,

    CONSTRAINT fk_investments_investor
        FOREIGN KEY (investor_id)
            REFERENCES investors (id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_investments_fund
        FOREIGN KEY (fund_id)
            REFERENCES funds (id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_investments_amount
        CHECK (amount > 0),

    CONSTRAINT ck_investments_nav
        CHECK (nav > 0),

    CONSTRAINT ck_investments_units
        CHECK (units > 0),

    CONSTRAINT ck_investments_status
        CHECK (
            status IN (
                       'PENDING',
                       'VALIDATED',
                       'CONFIRMED',
                       'FAILED',
                       'CANCELLED',
                       'REVERSED'
                )
            )
);

CREATE TABLE users
(
    -- Primary Key (matches GenerationType.IDENTITY)
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Core Columns with lengths and constraints
    username   VARCHAR(100) NOT NULL,
    password   VARCHAR(255) NOT NULL,              -- Defaults to 255 length since no length was specified
    email      VARCHAR(255) NOT NULL,              -- Defaults to 255 length since no length was specified
    role       VARCHAR(50)  NOT NULL,              -- String representation for the Enum

    -- Status flag with default matching @Builder.Default
    enabled    BOOLEAN      NOT NULL    DEFAULT TRUE,

    -- BaseEntity columns (Adjust fields if your BaseEntity contains more columns)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    version    BIGINT       NOT NULL    DEFAULT 0, -- Set to BIGINT to match your app's validation rule

    -- Constraints
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);
