CREATE TABLE outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       UUID         NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id   VARCHAR(100) NOT NULL,
    event_type     VARCHAR(100) NOT NULL,
    event_version  VARCHAR(20)  NOT NULL,
    topic_name     VARCHAR(255) NOT NULL,
    message_key    VARCHAR(255) NOT NULL,
    correlation_id VARCHAR(100) NOT NULL,
    payload        TEXT         NOT NULL,
    status         VARCHAR(30)  NOT NULL,
    retry_count    INTEGER      NOT NULL DEFAULT 0,
    next_retry_at  TIMESTAMP,
    published_at   TIMESTAMP,
    last_error     TEXT,

    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_outbox_events_event_id
        UNIQUE (event_id),

    CONSTRAINT ck_outbox_events_status
        CHECK (
            status IN (
                       'PENDING',
                       'PROCESSING',
                       'PUBLISHED',
                       'FAILED'
                )
            ),

    CONSTRAINT ck_outbox_events_retry_count
        CHECK (retry_count >= 0)
);

CREATE INDEX idx_outbox_status_created_at
    ON outbox_events (status, created_at);

CREATE INDEX idx_outbox_next_retry
    ON outbox_events (status, next_retry_at);

CREATE INDEX idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id);