CREATE TABLE processed_events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         UUID         NOT NULL,
    event_type       VARCHAR(100) NOT NULL,
    consumer_name    VARCHAR(150) NOT NULL,
    status           VARCHAR(30)  NOT NULL,
    topic_name       VARCHAR(255) NOT NULL,
    partition_number INTEGER,
    message_offset   BIGINT,
    correlation_id   VARCHAR(100),
    processed_at     TIMESTAMP,
    failure_reason   TEXT,

    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    version          BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_processed_events_event_consumer
        UNIQUE (event_id, consumer_name),

    CONSTRAINT ck_processed_events_status
        CHECK (
            status IN (
                       'PROCESSING',
                       'COMPLETED',
                       'FAILED'
                )
            )
);

CREATE INDEX idx_processed_events_status
    ON processed_events (status);

CREATE INDEX idx_processed_events_processed_at
    ON processed_events (processed_at);

CREATE TABLE investment_audit_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       UUID                     NOT NULL,
    event_type     VARCHAR(100)             NOT NULL,
    event_version  VARCHAR(20)              NOT NULL,
    correlation_id VARCHAR(100)             NOT NULL,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,

    investment_id  BIGINT                   NOT NULL,
    investor_id    BIGINT                   NOT NULL,
    investor_code  VARCHAR(50)              NOT NULL,
    fund_id        BIGINT                   NOT NULL,
    fund_code      VARCHAR(50)              NOT NULL,

    amount         NUMERIC(18, 2)           NOT NULL,
    nav            NUMERIC(18, 4)           NOT NULL,
    units          NUMERIC(18, 4)           NOT NULL,
    status         VARCHAR(30)              NOT NULL,

    created_at     TIMESTAMP                NOT NULL,
    updated_at     TIMESTAMP,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT uk_investment_audit_event_id
        UNIQUE (event_id),

    CONSTRAINT ck_investment_audit_status
        CHECK (
            status IN (
                       'PENDING',
                       'VALIDATED',
                       'CONFIRMED',
                       'FAILED',
                       'CANCELLED',
                       'REVERSED'
                )
            )
);

CREATE INDEX idx_investment_audit_investment
    ON investment_audit_events (investment_id);

CREATE INDEX idx_investment_audit_investor
    ON investment_audit_events (investor_id);

CREATE INDEX idx_investment_audit_fund
    ON investment_audit_events (fund_id);

CREATE INDEX idx_investment_audit_occurred_at
    ON investment_audit_events (occurred_at);