CREATE TABLE kafka_failed_events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         UUID,
    event_type       VARCHAR(100),
    correlation_id   VARCHAR(100),
    source_topic     VARCHAR(255) NOT NULL,
    source_partition INTEGER,
    source_offset    BIGINT,
    message_key      VARCHAR(255),
    payload          TEXT NOT NULL,
    failure_reason   TEXT NOT NULL,
    replayed         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    version          BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_kafka_failed_status ON kafka_failed_events (replayed);
CREATE INDEX idx_kafka_failed_event_id ON kafka_failed_events (event_id);
